# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        # The path to the xcworkspace to build. Mutually exclusive with `project`.
        project: src/SimpleView.xcodeproj
        # The action to perform (e.g. build, test, ...).
        action: build
    - name: List files
      run: ls -R *
    - name: Create DMG
      run: hdiutil create -volname SimpleView -srcfolder $(Build.SourcesDirectory)/output/build.sym/release/SimpleView.app -ov -format UDZO SimpleView.dmg
    - name: Publish SimpleView artifacts to GitHub
      uses: actions/upload-artifact@v1
      with:
        name: SimpleView
        path: SimpleView.dmg
